In [1]:
import pandas as pd
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
from string import punctuation
from collections import Counter
import numpy as np

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\mayan\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [2]:
data = gutenberg.raw('shakespeare-hamlet.txt')
with open('hamlet_data.txt', 'w') as file:
    file.write(data)

with open('hamlet_data.txt', 'r') as file:
    text = file.read()

original_text = text
text = text.replace('\n', ' ').replace('\r', ' ').replace('\t', ' ')
text = ''.join(c.lower() for c in text if c not in punctuation)
split_text = text.split(' ')
count_text = Counter(split_text)
count_text.pop('')
sorted_text = count_text.most_common()
sorted_text

[('the', 993),
 ('and', 862),
 ('to', 683),
 ('of', 610),
 ('i', 547),
 ('you', 522),
 ('my', 502),
 ('a', 497),
 ('it', 415),
 ('in', 384),
 ('that', 361),
 ('ham', 337),
 ('is', 315),
 ('not', 300),
 ('his', 285),
 ('this', 275),
 ('with', 254),
 ('your', 253),
 ('but', 249),
 ('for', 241),
 ('me', 228),
 ('lord', 212),
 ('as', 205),
 ('what', 200),
 ('he', 196),
 ('be', 191),
 ('so', 189),
 ('him', 178),
 ('haue', 175),
 ('king', 171),
 ('will', 149),
 ('no', 137),
 ('our', 130),
 ('we', 128),
 ('on', 123),
 ('are', 121),
 ('if', 111),
 ('all', 109),
 ('then', 108),
 ('shall', 107),
 ('by', 105),
 ('thou', 105),
 ('come', 104),
 ('or', 103),
 ('hamlet', 100),
 ('good', 98),
 ('do', 96),
 ('hor', 95),
 ('her', 95),
 ('let', 94),
 ('now', 92),
 ('thy', 90),
 ('from', 89),
 ('how', 89),
 ('more', 89),
 ('they', 88),
 ('enter', 85),
 ('at', 81),
 ('was', 81),
 ('oh', 81),
 ('most', 77),
 ('like', 77),
 ('there', 76),
 ('well', 70),
 ('tis', 69),
 ('know', 69),
 ('would', 68),
 ('selfe',

In [3]:
tokenized_text = {w : i+1 for i, (w, c) in enumerate(sorted_text)}
tokenized_text

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'my': 7,
 'a': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'from': 53,
 'how': 54,
 'more': 55,
 'they': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'most': 61,
 'like': 62,
 'there': 63,
 'well': 64,
 'tis': 65,
 'know': 66,
 'would': 67,
 'selfe': 68,
 'them': 69,
 'may': 70,
 'loue': 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 8

In [4]:
len(tokenized_text)

4799

In [5]:
original_text = ''.join(c.lower() for c in original_text if c not in punctuation)
original_text

'the tragedie of hamlet by william shakespeare 1599\n\n\nactus primus scoena prima\n\nenter barnardo and francisco two centinels\n\n  barnardo whos there\n  fran nay answer me stand  vnfold\nyour selfe\n\n   bar long liue the king\n\n   fran barnardo\n  bar he\n\n   fran you come most carefully vpon your houre\n\n   bar tis now strook twelue get thee to bed francisco\n\n   fran for this releefe much thankes tis bitter cold\nand i am sicke at heart\n\n   barn haue you had quiet guard\n  fran not a mouse stirring\n\n   barn well goodnight if you do meet horatio and\nmarcellus the riuals of my watch bid them make hast\nenter horatio and marcellus\n\n  fran i thinke i heare them stand whos there\n  hor friends to this ground\n\n   mar and leigemen to the dane\n\n   fran giue you good night\n\n   mar o farwel honest soldier who hath relieud you\n  fra barnardo has my place giue you goodnight\n\nexit fran\n\n  mar holla barnardo\n\n   bar say what is horatio there\n  hor a peece of him\n\n  

In [6]:
original_split = original_text.split('\n')
original_split = [x for x in original_split if x != '']
original_split

['the tragedie of hamlet by william shakespeare 1599',
 'actus primus scoena prima',
 'enter barnardo and francisco two centinels',
 '  barnardo whos there',
 '  fran nay answer me stand  vnfold',
 'your selfe',
 '   bar long liue the king',
 '   fran barnardo',
 '  bar he',
 '   fran you come most carefully vpon your houre',
 '   bar tis now strook twelue get thee to bed francisco',
 '   fran for this releefe much thankes tis bitter cold',
 'and i am sicke at heart',
 '   barn haue you had quiet guard',
 '  fran not a mouse stirring',
 '   barn well goodnight if you do meet horatio and',
 'marcellus the riuals of my watch bid them make hast',
 'enter horatio and marcellus',
 '  fran i thinke i heare them stand whos there',
 '  hor friends to this ground',
 '   mar and leigemen to the dane',
 '   fran giue you good night',
 '   mar o farwel honest soldier who hath relieud you',
 '  fra barnardo has my place giue you goodnight',
 'exit fran',
 '  mar holla barnardo',
 '   bar say what i

In [7]:
input_sequences = []
for line in original_split:
    token_line = [tokenized_text[word] for word in line.split(' ') if word != '']
    for i in range(1, len(token_line)):
        n_gram_sequence = token_line[:i+1]
        input_sequences.append(n_gram_sequence)
print(input_sequences)
print(len(input_sequences))
features = max(len(x) for x in input_sequences)

[[1, 683], [1, 683, 4], [1, 683, 4, 45], [1, 683, 4, 45, 41], [1, 683, 4, 45, 41, 1857], [1, 683, 4, 45, 41, 1857, 1858], [1, 683, 4, 45, 41, 1857, 1858, 1859], [1168, 1860], [1168, 1860, 1861], [1168, 1860, 1861, 1862], [57, 406], [57, 406, 2], [57, 406, 2, 1169], [57, 406, 2, 1169, 180], [57, 406, 2, 1169, 180, 1863], [406, 1170], [406, 1170, 63], [407, 161], [407, 161, 374], [407, 161, 374, 21], [407, 161, 374, 21, 247], [407, 161, 374, 21, 247, 875], [18, 68], [449, 223], [449, 223, 257], [449, 223, 257, 1], [449, 223, 257, 1, 30], [407, 406], [449, 25], [407, 6], [407, 6, 43], [407, 6, 43, 61], [407, 6, 43, 61, 1864], [407, 6, 43, 61, 1864, 96], [407, 6, 43, 61, 1864, 96, 18], [407, 6, 43, 61, 1864, 96, 18, 566], [449, 65], [449, 65, 51], [449, 65, 51, 1865], [449, 65, 51, 1865, 567], [449, 65, 51, 1865, 567, 375], [449, 65, 51, 1865, 567, 375, 80], [449, 65, 51, 1865, 567, 375, 80, 3], [449, 65, 51, 1865, 567, 375, 80, 3, 321], [449, 65, 51, 1865, 567, 375, 80, 3, 321, 1169], [40

In [8]:
padded_sequences = np.zeros((len(input_sequences), features))
for i in range(len(input_sequences)):
    padded_sequences[i, features-len(input_sequences[i]):] = np.array(input_sequences[i])
padded_sequences = padded_sequences.astype(int)
print(padded_sequences)

[[   0    0    0 ...    0    1  683]
 [   0    0    0 ...    1  683    4]
 [   0    0    0 ...  683    4   45]
 ...
 [   0    0    0 ...    4   45 1042]
 [   0    0    0 ...   45 1042    4]
 [   0    0    0 ... 1042    4  192]]
